"""OAuth 2.0 authorization-code exchange (issue #12 follow-up).

`/auth/login` stayed correctly deleted when login moved to the frontend
(docs/adr/0004) -- the frontend builds its own consent URL from the public
client id, and doesn't need this service for that.

`/auth/callback` was deleted in the same pass, which was a mistake: the
frontend's own callback (src/frontend/app/onboarding/callback/route.ts)
deliberately never holds the OAuth *client secret* -- only this service's
env does -- so it cannot exchange the authorization code itself. It calls
this endpoint over server-to-server HTTP instead. This service is the only
thing that can produce a refresh token, so it's also the thing that
encrypts and stores it (app.services.firestore_creds.store_refresh_token),
now in Firestore/KMS instead of Secret Manager. See docs/adr/0004's
amendment for why the encrypter/decrypter split from the original issue #12
design doesn't apply here.
"""
from fastapi import APIRouter, HTTPException, Request
from google.oauth2 import id_token as gid
from google.auth.transport import requests as grequests
from google_auth_oauthlib.flow import Flow

from app.config import settings
from app.services import firestore_creds

router = APIRouter(prefix="/auth", tags=["auth"])


def _flow(state: str | None = None) -> Flow:
    client_config = {
        "web": {
            "client_id": settings.google_client_id,
            "client_secret": settings.google_client_secret,
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "redirect_uris": [settings.oauth_redirect_uri],
        }
    }
    return Flow.from_client_config(
        client_config, scopes=settings.scopes, state=state,
        redirect_uri=settings.oauth_redirect_uri,
        # The frontend builds its own consent URL (lib/googleOAuth.ts) with no
        # PKCE code_challenge. If this Flow autogenerated its own
        # code_verifier, the exchange would send a code_verifier Google never
        # saw a matching challenge for, and fail. Keep this False.
        autogenerate_code_verifier=False,
    )


@router.get("/callback")
def callback(
    request: Request,
    code: str | None = None,
    uid: str | None = None,
    error: str | None = None,
):
    if error:
        raise HTTPException(status_code=400, detail=f"OAuth error: {error}")
    if not code:
        raise HTTPException(status_code=400, detail="Missing authorization code")
    if not uid:
        # uid is optional in the signature (not a required path param) purely
        # so this is a clean 400, not FastAPI's 422 -- the frontend still
        # needs to be changed to start sending it (it doesn't yet; see the
        # migration notes this task's summary flags).
        raise HTTPException(status_code=400, detail="Missing uid (Firebase Auth UID)")

    flow = _flow()
    flow.fetch_token(code=code)
    creds = flow.credentials

    # Verify id_token -> stable Google identity (kept for frontend compat --
    # see API_CONTRACT.md's note on the user_id / google_sub collision).
    info = gid.verify_oauth2_token(
        creds.id_token, grequests.Request(), settings.google_client_id
    )
    google_sub, email = info["sub"], info.get("email")

    if not creds.refresh_token:
        # Can happen if Google skipped consent; prompt="consent" (set by the
        # frontend's auth URL) should prevent it.
        raise HTTPException(status_code=500, detail="No refresh token returned; retry login")

    firestore_creds.store_refresh_token(
        uid=uid, google_sub=google_sub, refresh_token=creds.refresh_token
    )

    # Response shape is frozen (API_CONTRACT.md) -- the frontend reads
    # payload.user_id and stores it as google_sub. firebase_uid is additive.
    return {
        "user_id": google_sub,
        "email": email,
        "status": "connected",
        "firebase_uid": uid,
    }
