import type { Metadata } from "next";
import Link from "next/link";
import { LegalLayout, LegalList, Strong, type LegalSection } from "@/components/site/LegalLayout";
import { LEGAL, SUBPROCESSORS } from "@/data/legal";

export const metadata: Metadata = {
  title: "Privacy policy",
  description:
    "What Classistant collects, why it needs it, who else sees it, how long it is kept, and how to get rid of it.",
};

const SECTIONS: LegalSection[] = [
  {
    id: "scope",
    heading: "Who this covers",
    body: (
      <>
        <p>
          This policy applies to {LEGAL.entity} (&ldquo;{LEGAL.operatingName}&rdquo;,
          &ldquo;we&rdquo;, &ldquo;us&rdquo;), and to everything you do on classistant.ca and
          through the Classistant text and voice assistant.
        </p>
        <p>
          We are a Canadian organisation and we handle personal information under the federal{" "}
          <Strong>Personal Information Protection and Electronic Documents Act (PIPEDA)</Strong>,
          plus provincial privacy law where it applies to you, including Quebec&rsquo;s Law 25.
          Our commercial messages and automated texts follow{" "}
          <Strong>Canada&rsquo;s Anti-Spam Legislation (CASL)</Strong>.
        </p>
        <p>
          Classistant is an independent product. We are not affiliated with, endorsed by, or
          operated by any university, college, or by Google LLC.
        </p>
      </>
    ),
  },
  {
    id: "collect",
    heading: "What we collect",
    body: (
      <>
        <p>We collect four kinds of information, and no more than the assistant needs to work.</p>
        <p>
          <Strong>Information you give us, at sign-up or later.</Strong>
        </p>
        <LegalList
          items={[
            "Your full name and your school email address.",
            "Your school, so we know which portal to sign in to.",
            "Your Canadian mobile number, which is where texts and calls go.",
            "Your student portal username and password, when the assistant asks for them.",
            "Your preferences: how hard the assistant should push, your quiet hours, and whether you want phone calls.",
          ]}
        />
        <p>
          <Strong>Information from your Google account, with your consent.</Strong> When you
          sign in with Google you grant scoped access. We read course-related email and
          announcements, read and write calendar events, and read syllabus and course files in
          your Drive. We send email only from your address and only after you approve the
          specific message.
        </p>
        <p>
          <Strong>Information from your school portal.</Strong> Using the credentials you
          supplied, we sign in to your portal on your behalf and read your course list, class
          and exam schedule, posted grades, course content, and syllabus documents.
        </p>
        <p>
          <Strong>Information generated by using the service.</Strong> The texts and calls
          between you and the assistant, the deadlines and tasks it derives, how quickly you tend
          to complete work, and basic technical logs such as IP address, browser type, and error
          traces.
        </p>
      </>
    ),
  },
  {
    id: "use",
    heading: "Why we use it",
    body: (
      <>
        <p>We use your information only for the following purposes.</p>
        <LegalList
          items={[
            "To build and maintain your semester: courses, schedule, deadlines, and exam dates.",
            "To write those items into your Google Calendar and our task database.",
            "To decide what to remind you about, when, and how insistently, based on your own past pace.",
            "To detect new grades and course announcements and tell you about them.",
            "To draft email you have asked for, and send it once you approve it.",
            "To place the voice calls you opted into.",
            "To keep the service running, debug failures, and prevent abuse.",
          ]}
        />
        <p>
          We do <Strong>not</Strong> sell your personal information. We do <Strong>not</Strong>{" "}
          use it for advertising. We do <Strong>not</Strong> use the contents of your school
          email, portal, or Drive to train general-purpose machine learning models.
        </p>
      </>
    ),
  },
  {
    id: "google",
    heading: "How we treat Google data",
    body: (
      <>
        <p>
          Classistant&rsquo;s use of information received from Google APIs follows the{" "}
          <Strong>Google API Services User Data Policy</Strong>, including its Limited Use
          requirements. In practice that means Google user data is used only to provide and
          improve the features you can see, is never transferred to anyone except as needed to
          run the service or where you direct it, is never used for advertising, and is never
          read by a human except with your explicit permission, to resolve a support issue you
          reported, or where the law requires it.
        </p>
        <p>
          You can withdraw our Google access at any time from your Google account permissions
          page, without contacting us first. Doing so stops calendar writes and email scanning
          immediately.
        </p>
      </>
    ),
  },
  {
    id: "credentials",
    heading: "Your school portal password",
    body: (
      <>
        <p>
          Course pages and posted grades sit behind your portal login and there is no API for
          them, so the assistant signs in as you. That means we have to hold the credential.
        </p>
        <LegalList
          items={[
            "It is encrypted at rest in Google Firestore using envelope encryption, with keys held in a separate key management service.",
            "It is decrypted only inside an isolated browser session that is signing in to your school's own login page.",
            "It is never displayed back to you, never written to application logs, and never sent to any destination other than your school.",
            "No Classistant staff member can read it.",
            "Deleting your account destroys it immediately rather than on a retention schedule.",
          ]}
        />
        <p>
          If your school&rsquo;s own IT policy forbids sharing your credentials with a third
          party, do not enter them. That is a rule between you and your school, and it is your
          responsibility to check it.
        </p>
      </>
    ),
  },
  {
    id: "sharing",
    heading: "Who else sees your data",
    body: (
      <>
        <p>
          We share personal information with the service providers below, only to the extent each
          one needs it to do its job. They are bound by contract to protect it and to use it for
          no other purpose.
        </p>
        <div className="overflow-x-auto rounded-xl ring-1 ring-line">
          <table className="w-full min-w-[36rem] border-collapse text-left text-[0.88rem]">
            <thead>
              <tr className="bg-paper">
                <th className="px-4 py-3 font-semibold text-ink-900">Provider</th>
                <th className="px-4 py-3 font-semibold text-ink-900">What it does</th>
                <th className="px-4 py-3 font-semibold text-ink-900">What it sees</th>
                <th className="px-4 py-3 font-semibold text-ink-900">Where</th>
              </tr>
            </thead>
            <tbody>
              {SUBPROCESSORS.map((p) => (
                <tr key={p.name} className="border-t border-line-soft align-top">
                  <td className="px-4 py-3 font-medium text-ink-900">{p.name}</td>
                  <td className="px-4 py-3">{p.purpose}</td>
                  <td className="px-4 py-3">{p.data}</td>
                  <td className="px-4 py-3">{p.region}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <p>
          Some of these providers operate outside Canada, so your information may be stored or
          processed in the United States and elsewhere. While it is in another country it is
          subject to that country&rsquo;s laws, including lawful access by its courts and law
          enforcement.
        </p>
        <p>
          We will also disclose information if we are legally required to, or where it is
          necessary to protect someone&rsquo;s safety. If we are ever bought or merged, your
          information may transfer to the new owner under this same policy, and we will tell you
          before that happens.
        </p>
      </>
    ),
  },
  {
    id: "messages",
    heading: "Texts and phone calls",
    body: (
      <>
        <p>
          You give express consent to automated texts during onboarding, and again for voice
          calls if you turn them on. Standard message and data rates from your carrier may apply.
        </p>
        <LegalList
          items={[
            <>
              Reply <Strong>STOP</Strong> to end all messages.
            </>,
            <>
              Reply <Strong>STOP CALLS</Strong> to keep texts but end voice calls.
            </>,
            <>
              Reply <Strong>HELP</Strong> for support, or email {LEGAL.contactEmail}.
            </>,
            <>
              Reply <Strong>DELETE</Strong> to close your account and erase your data, or use{" "}
              <Link href="/delete-my-data" className="font-semibold text-brand-600 hover:underline">
                delete my data
              </Link>
              .
            </>,
          ]}
        />
        <p>
          Message content is retained so the assistant has conversational context. Voice calls
          are not recorded by default. If we ever need to record one for quality or safety, you
          will be told at the start of that call and can decline.
        </p>
      </>
    ),
  },
  {
    id: "retention",
    heading: "How long we keep things",
    body: (
      <LegalList
        items={[
          "Account details and preferences: until you delete your account.",
          "Portal credentials: until you delete your account or remove your school, then destroyed immediately.",
          "Course data, deadlines, and grades: for the current term plus twelve months, so the assistant can pace you better next semester. You can clear it sooner.",
          "Message and call history: twenty-four months.",
          "Technical logs: ninety days.",
          "Anything we are required to keep by law, for as long as the law requires.",
        ]}
      />
    ),
  },
  {
    id: "security",
    heading: "How we protect it",
    body: (
      <>
        <p>
          Data is encrypted in transit with TLS and at rest. Credentials get a second layer of
          application-level encryption. Access to production systems is limited to the people who
          need it, requires multi-factor authentication, and is logged.
        </p>
        <p>
          No system is perfectly secure. If a breach happens that creates a real risk of
          significant harm to you, we will notify you and the Office of the Privacy Commissioner
          of Canada as PIPEDA requires.
        </p>
      </>
    ),
  },
  {
    id: "rights",
    heading: "Your rights",
    body: (
      <>
        <p>You can, at any time and free of charge:</p>
        <LegalList
          items={[
            "Ask what personal information we hold about you and get a copy of it.",
            "Have anything inaccurate corrected.",
            "Delete your account and everything attached to it.",
            "Withdraw your consent to texts, to calls, or to Google access, without losing the rest.",
            "Ask us to explain how an automated decision about your reminders was made.",
            "Complain to us, and then to the Office of the Privacy Commissioner of Canada if you are not satisfied.",
          ]}
        />
        <p>
          Email {LEGAL.privacyEmail} and we will respond within thirty days, which is the
          deadline PIPEDA sets. To delete, start at{" "}
          <Link href="/delete-my-data" className="font-semibold text-brand-600 hover:underline">
            delete my data
          </Link>
          , which writes the request for you and sets out exactly what disappears.
        </p>
      </>
    ),
  },
  {
    id: "age",
    heading: "Age",
    body: (
      <p>
        Classistant is for post-secondary students and you must be at least sixteen to use it. We
        do not knowingly collect information from anyone younger. If we learn that we have, we
        delete it.
      </p>
    ),
  },
  {
    id: "changes",
    heading: "Changes to this policy",
    body: (
      <p>
        If we change this policy in a way that materially affects you, we will text you and email
        you at least thirty days before it takes effect, so you have time to leave if you
        disagree. The date at the top always reflects the current version.
      </p>
    ),
  },
  {
    id: "contact",
    heading: "Contact",
    body: (
      <>
        <p>
          Our privacy officer is reachable at{" "}
          <a href={`mailto:${LEGAL.privacyOfficer}`} className="font-semibold text-brand-600 hover:underline">
            {LEGAL.privacyOfficer}
          </a>
          .
        </p>
        <p>
          {LEGAL.entity}
          <br />
          {LEGAL.address}
        </p>
        <p>
          See also our{" "}
          <Link href="/terms" className="font-semibold text-brand-600 hover:underline">
            terms of service
          </Link>
          .
        </p>
      </>
    ),
  },
];

export default function PrivacyPage() {
  return (
    <LegalLayout
      title="Privacy policy"
      lastUpdated={LEGAL.lastUpdated}
      intro={
        <>
          Classistant needs unusually deep access to your school life to be useful. This page is
          the plain version of what that means: what we take, why, who else touches it, and how
          to make us forget all of it.
        </>
      }
      sections={SECTIONS}
    />
  );
}
