/**
 * Classy's number, and the two links that put it to use.
 *
 * The number is not a secret. It is the number printed on the contact card we
 * hand to students, so it belongs in the client bundle rather than in an env
 * var that would have to be exposed with NEXT_PUBLIC_ anyway.
 *
 * ## It is hand-synced in three places, and nothing checks that
 *
 *   1. here, for what the site shows and links to
 *   2. `scripts/build-vcard.mts`, which bakes it into public/classy.vcf
 *   3. `TWILIO_FROM_NUMBER` in the deployed Twilio functions
 *
 * If the number ever changes, change all three and re-run `npm run build:vcard`.
 * A mismatch fails silently and in the worst possible way: the site tells a
 * student to text a number that nothing answers on, and the onboarding they just
 * finished looks broken.
 */
export const CLASSY_TEL = "+13654007007";

/** How it is written on screen. Grouped, because ten unbroken digits are
 *  something you read twice. */
export const CLASSY_TEL_DISPLAY = "+1 365 400 7007";

/**
 * The compose link.
 *
 * `sms:` with no body on purpose. A prefilled `?body=` is tempting and is the
 * one part of this URI scheme phones disagree about: iOS wanted `&body=` for
 * years, Android follows RFC 5724 and wants `?body=`, and the `?&body=` hack
 * that covers both is exactly the kind of thing that works on the two handsets
 * you tested and opens a blank Messages app on the third. Opening the thread on
 * the right number is the whole job here; the first line to send is suggested in
 * the copy beside it instead, where it cannot break anything.
 */
export const CLASSY_SMS_HREF = `sms:${CLASSY_TEL}`;

/** The contact card, generated by scripts/build-vcard.mts. Saving it is what
 *  makes the replies arrive from a name and a face rather than from ten digits
 *  the student does not recognise at 7am. */
export const CLASSY_VCARD_HREF = "/classy.vcf";
